/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Avin
 */
public class ResetPassword extends javax.swing.JPanel {

    /**
     * Creates new form ResetPassword
     */
    
    public Frame frame;
  
        
    public void clearResetFields() {
        passwordFld.setText(null);
        confpassFld.setText(null);
        changeBtn.setEnabled(false);
    }
    
    public ResetPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changeBtn = new javax.swing.JButton();
        passwordFld = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        confpassFld = new javax.swing.JPasswordField();
        backBtn = new javax.swing.JButton();
        passwordLabel = new javax.swing.JLabel();
        confpassLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(111, 36));
        setMinimumSize(new java.awt.Dimension(111, 36));
        setPreferredSize(new java.awt.Dimension(111, 36));

        changeBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        changeBtn.setText("CHANGE");
        changeBtn.setEnabled(false);
        changeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBtnActionPerformed(evt);
            }
        });

        passwordFld.setBackground(new java.awt.Color(240, 240, 240));
        passwordFld.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordFld.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "PASSWORD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        passwordFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFldActionPerformed(evt);
            }
        });
        passwordFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordFldKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SECURITY Svcs");
        jLabel1.setToolTipText("");

        confpassFld.setBackground(new java.awt.Color(240, 240, 240));
        confpassFld.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confpassFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confpassFld.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "CONFIRM PASSWORD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        confpassFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confpassFldKeyReleased(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backBtn.setText("<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        confpassLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confpassFld)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordFld)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confpassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backBtn)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordFld, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confpassFld, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confpassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void changeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBtnActionPerformed
        
        frame.reset(frame.getUserEmail(), passwordFld.getText());
        clearResetFields();
        JOptionPane.showMessageDialog(this, "Password Changed Successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        frame.loginNav();
       
    }//GEN-LAST:event_changeBtnActionPerformed

    private void passwordFldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFldKeyReleased
        if(!passwordFld.getText().equals("")) {
            checkPassStrength();
            if (!confpassFld.getText().equals("")) {
                if (isPassSame()){
                        if(checkPassStrength() != 5) {
                            confpassLabel.setText("Passwords MATCH but NOT STRONG enough");
                            confpassLabel.setForeground(Color.RED);
                            changeBtn.setEnabled(false);
                        } else {
                            confpassLabel.setText("Passwords MATCH");
                            confpassLabel.setForeground(Color.GREEN);
                            changeBtn.setEnabled(true);
                        }
                } else {
                    confpassLabel.setText("Passwords DO NOT MATCH");
                    confpassLabel.setForeground(Color.RED);
                    changeBtn.setEnabled(false);
                }
            } else {
                confpassLabel.setText("");
                changeBtn.setEnabled(false);
            }
        } else {
            passwordLabel.setText("");
            confpassLabel.setText("");
            changeBtn.setEnabled(false);
        }
    }//GEN-LAST:event_passwordFldKeyReleased

    private void confpassFldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confpassFldKeyReleased
        if(confpassFld.getText().equals("")) confpassLabel.setText("");
        else if (isPassSame()){

                if(checkPassStrength() != 5) {
                    confpassLabel.setText("Passwords MATCH but NOT STRONG enough");
                    confpassLabel.setForeground(Color.RED);
                    changeBtn.setEnabled(false);
                } else {
                    confpassLabel.setText("Passwords MATCH");
                    confpassLabel.setForeground(Color.GREEN);
                    changeBtn.setEnabled(true);
                }
         
            
        } else{
            confpassLabel.setText("Passwords DO NOT MATCH");
            confpassLabel.setForeground(Color.RED);
            changeBtn.setEnabled(false);
        }
    }//GEN-LAST:event_confpassFldKeyReleased

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        clearResetFields();
        frame.loginNav();
    }//GEN-LAST:event_backBtnActionPerformed

    private void passwordFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFldActionPerformed

        public boolean checkUsernameValidity(String username){
        if(username.length() < 4 || username.length() > 16) return false;
        
        for(int x = 0; x < username.length(); x++){
            if(username.charAt(x) > 31 && username.charAt(x) < 48 || 
                    username.charAt(x) > 57 && username.charAt(x) < 65 || 
                    username.charAt(x) > 90 && username.charAt(x) < 97 || 
                    username.charAt(x) > 122 && username.charAt(x) < 127){
                return false;
            }
        }
        
        return true;
    }
    

    
    public int getPassStrength(String password){
        int strength = 0;
        boolean checkLower = false, checkUpper = false, checkSpecial = false, checkNumerical = false;
        
        // Check Length
        if(password.length() < 12 || password.length() > 64) return -1;
        else strength += 1;
        
        // Check Lower Case
        for(int x = 0; x < password.length(); x++){
            if(password.charAt(x) > 96 && password.charAt(x) < 123){
                strength += 1;
                checkLower = true;
                break;
            }
        }
        
        // Check Upper Case
        for(int x = 0; x < password.length(); x++){
            if(password.charAt(x) > 64 && password.charAt(x) < 91){
                strength += 1;
                checkUpper = true;
                break;
            }
        }
        
        // Check Special
        for(int x = 0; x < password.length(); x++){
            if(password.charAt(x) > 31 && password.charAt(x) < 48 || password.charAt(x) > 57 && password.charAt(x) < 65 || password.charAt(x) > 90 && password.charAt(x) < 97 || password.charAt(x) > 122 && password.charAt(x) < 127){
                strength += 1;
                checkSpecial = true;
                break;
            }
        }
        
        // Check Numerical
        for(int x = 0; x < password.length(); x++){
            if(password.charAt(x) > 47 && password.charAt(x) < 58){
                strength += 1;
                checkNumerical = true;
                break;
            }
        }
        
        String hint = "";
        if(!checkLower) hint += "Must at least have 1 LOWER CASE character.<br>";
        if(!checkUpper) hint += "Must at least have 1 UPPER CASE character.<br>";
        if(!checkSpecial) hint += "Must at least have 1 SPECIAL character.<br>";
        if(!checkNumerical) hint += "Must at least have 1 NUMERICAL character.<br><br>";
        
        passwordLabel.setText("<html>" + hint);
        
        return strength;
    }
    
    public int checkPassStrength(){
        int currentStrength = getPassStrength(passwordFld.getText());
        
        if(currentStrength <= 0){
            if (passwordFld.getText().length() < 12)
                passwordLabel.setText("Password BELOW MINIMUM requirement of 12 characters");
            else if(passwordFld.getText().length() > 64)
                passwordLabel.setText("Password EXCEEDS MAXIMUM of 64 characters");
            passwordLabel.setForeground(Color.RED);
        } else if(currentStrength <= 2){
            passwordLabel.setText(passwordLabel.getText() + "Current Password Strength: WEAK</html>");
            passwordLabel.setForeground(Color.RED);
        } else if(currentStrength <= 4){
            passwordLabel.setText(passwordLabel.getText() + "Current Password Strength: MODERATE</html>");
            passwordLabel.setForeground(Color.ORANGE);
        } else if(currentStrength == 5){
            passwordLabel.setText(passwordLabel.getText() + "Current Password Strength: STRONG</html>");
            passwordLabel.setForeground(Color.GREEN);
        }
        
        return currentStrength;
    }
    
    public boolean isPassSame(){
        return confpassFld.getText().equals(passwordFld.getText());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton changeBtn;
    private javax.swing.JTextField confpassFld;
    private javax.swing.JLabel confpassLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField passwordFld;
    private javax.swing.JLabel passwordLabel;
    // End of variables declaration//GEN-END:variables
}
